export const colors = {
	// DARK
    background: "#3B4454",
    foreground: "#c9c9d6",
	navbackground: "#212935",
    primary: "#ebb275",
    primaryforeground: "#fff",
    secondary: "#212935",
    secondaryforeground: "#222",
    accent: "#BFEFE4",
    accentforeground: "#222",
    destructive: "#DB5461",
    destructiveforeground: "#fff",
	unfilledcolor: '#ffffff33',
	// LIGHT
    // background: "#f3f3f3",
    // backgroundother: "#000",
    // foreground: "#020202",
	// navbackground: "#1e1e1f",
    // primary: "#4ba623",
    // primaryforeground: "#ceced6",
    // secondary: "#fff",
	// accent: "#45ff29",
	// accentforeground: "#000",
    // secondaryforeground: "#fff",
    // destructive: "#DB5461",
    // destructiveforeground: "#fff",
	// unfilledcolor: '#ffffff33',
}